#!/usr/bin/env bash
set -euo pipefail

# Usage: ./check_db_schema.sh [path to .env]
ENV_FILE=${1:-$(dirname "$0")/env.example}
if [[ -f "$ENV_FILE" ]]; then
  set -o allexport
  source "$ENV_FILE"
  set +o allexport
else
  echo "Env file not found: $ENV_FILE" >&2
  exit 2
fi

MYSQL=${MYSQL_CMD:-mysql}

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "Exporting schema metadata for Laravel DB ($LARAVEL_DB_NAME)"
$MYSQL -h "$LARAVEL_DB_HOST" -P "$LARAVEL_DB_PORT" -u "$LARAVEL_DB_USER" -p"$LARAVEL_DB_PASS" -N -e \
"SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$LARAVEL_DB_NAME' ORDER BY TABLE_NAME, ORDINAL_POSITION;" > "$TMPDIR/laravel_columns.tsv"

echo "Exporting schema metadata for Symfony DB ($SYMFONY_DB_NAME)"
$MYSQL -h "$SYMFONY_DB_HOST" -P "$SYMFONY_DB_PORT" -u "$SYMFONY_DB_USER" -p"$SYMFONY_DB_PASS" -N -e \
"SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$SYMFONY_DB_NAME' ORDER BY TABLE_NAME, ORDINAL_POSITION;" > "$TMPDIR/symfony_columns.tsv"

echo "Diffing columns..."
if diff -u "$TMPDIR/laravel_columns.tsv" "$TMPDIR/symfony_columns.tsv"; then
  echo "Column definitions match.";
else
  echo "Column definition differences detected." >&2
fi

echo "Also checking indexes and foreign keys (statements may vary by DB user)."
$MYSQL -h "$LARAVEL_DB_HOST" -P "$LARAVEL_DB_PORT" -u "$LARAVEL_DB_USER" -p"$LARAVEL_DB_PASS" -N -e \
"SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, SEQ_IN_INDEX, COLUMN_NAME, INDEX_TYPE FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$LARAVEL_DB_NAME' ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;" > "$TMPDIR/laravel_indexes.tsv"
$MYSQL -h "$SYMFONY_DB_HOST" -P "$SYMFONY_DB_PORT" -u "$SYMFONY_DB_USER" -p"$SYMFONY_DB_PASS" -N -e \
"SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, SEQ_IN_INDEX, COLUMN_NAME, INDEX_TYPE FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$SYMFONY_DB_NAME' ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;" > "$TMPDIR/symfony_indexes.tsv"

diff -u "$TMPDIR/laravel_indexes.tsv" "$TMPDIR/symfony_indexes.tsv" || echo "Index differences found or none."

$MYSQL -h "$LARAVEL_DB_HOST" -P "$LARAVEL_DB_PORT" -u "$LARAVEL_DB_USER" -p"$LARAVEL_DB_PASS" -N -e \
"SELECT KCU.TABLE_NAME, KCU.COLUMN_NAME, KCU.REFERENCED_TABLE_NAME, KCU.REFERENCED_COLUMN_NAME, RC.UPDATE_RULE, RC.DELETE_RULE FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC ON KCU.CONSTRAINT_NAME = RC.CONSTRAINT_NAME AND KCU.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA WHERE KCU.TABLE_SCHEMA = '$LARAVEL_DB_NAME' AND KCU.REFERENCED_TABLE_NAME IS NOT NULL ORDER BY KCU.TABLE_NAME, KCU.CONSTRAINT_NAME;" > "$TMPDIR/laravel_fks.tsv"

$MYSQL -h "$SYMFONY_DB_HOST" -P "$SYMFONY_DB_PORT" -u "$SYMFONY_DB_USER" -p"$SYMFONY_DB_PASS" -N -e \
"SELECT KCU.TABLE_NAME, KCU.COLUMN_NAME, KCU.REFERENCED_TABLE_NAME, KCU.REFERENCED_COLUMN_NAME, RC.UPDATE_RULE, RC.DELETE_RULE FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC ON KCU.CONSTRAINT_NAME = RC.CONSTRAINT_NAME AND KCU.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA WHERE KCU.TABLE_SCHEMA = '$SYMFONY_DB_NAME' AND KCU.REFERENCED_TABLE_NAME IS NOT NULL ORDER BY KCU.TABLE_NAME, KCU.CONSTRAINT_NAME;" > "$TMPDIR/symfony_fks.tsv"

diff -u "$TMPDIR/laravel_fks.tsv" "$TMPDIR/symfony_fks.tsv" || echo "FK differences found or none."

echo "DB schema compare finished. Review diffs above for incompatibilities."
